version: '3.8'

services:
  backend:
    image: 167807621628.dkr.ecr.eu-west-1.amazonaws.com/playmetrix:backend-latest
    networks:
      - playmetrix_network
    logging:
      driver: awslogs
      options:
        awslogs-group: "backend-logs"
        awslogs-region: "eu-west-1"

  frontend:
    image: 167807621628.dkr.ecr.eu-west-1.amazonaws.com/playmetrix:frontend-latest
    networks:
      - playmetrix_network
    logging:
      driver: awslogs
      options:
        awslogs-group: "frontend-logs"
        awslogs-region: "eu-west-1"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/playmetrix_docker_compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - playmetrix_network
    logging:
      driver: awslogs
      options:
        awslogs-group: "nginx-logs"
        awslogs-region: "eu-west-1"

networks:
  playmetrix_network:
    driver: bridge


