version: '3.8'

services:
  backend:
    image: 167807621628.dkr.ecr.eu-west-1.amazonaws.com/playmetrix:backend-latest
    ports:
      - "8000:8000"
    networks:
      - playmetrix_network

  frontend:
    image: 167807621628.dkr.ecr.eu-west-1.amazonaws.com/playmetrix:frontend-latest
    ports:
      - "80:80"
    networks:
      - playmetrix_network

networks:
  playmetrix_network:
    driver: bridge
