version: '3.8'

services:
  backend:
    image: 167807621628.dkr.ecr.eu-west-1.amazonaws.com/playmetrix:backend-latest
    networks:
      - playmetrix_network

  frontend:
    image: 167807621628.dkr.ecr.eu-west-1.amazonaws.com/playmetrix:frontend-latest
    networks:
      - playmetrix_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - playmetrix_network

networks:
  playmetrix_network:
    driver: bridge
